---
# Build script
sln : 'AndroidApp\AndroidApp.sln'
deployment_directory: 'deployment'
nuget: '..\utils\.nuget\NuGet.exe'
xamarin_component: '..\utils\xamarin-component\xamarin-component.exe'
tasks:
    - clean_directory:
        - directory: $(deployment_directory)
    - restore_nuget_packages:
        - nuget_exe : $(nuget)
        - solution: $(sln)
    - restore_xam_components:
        - xam_exe: $(xamarin_component)
        - solution: $(sln)
    - msbuild_build_project:
        - project: 'AndroidApp\AndroidApp.csproj'
        - targets : 'Clean,SignAndroidPackage'
        - configuration: 'Release'
# finish
