---
# Build script
sln : 'AndroidTestsApp.sln'
targets:
    - Clean
    - Install
nuget: '..\utils\.nuget\NuGet.exe'
xamarin_component: '..\utils\xamarin-component\xamarin-component.exe'
touch_server_exe: '..\utils\Touch.Server.Android.exe'
tasks:
    - clean_directory:
        - directory: 'deployment'
    - fulfill_file_template:
        - ip: 10.38.10.134
        - port: 55555
        - is_automated: true
        - is_remote: true
        - format: nunit2
        - template: 'file_templates_folder\t_TestResultsConfig.txt'
        - destination: 'C:\Users\maa\Dropbox\Projects\baide\samples\AndroidTestsApp\TestConfiguration\TestResultsConfig.cs'
    - restore_nuget_packages:
        - nuget_exe : nuget
        - solution: sln
    - restore_xam_components:
        - xam_exe: xamarin_component
        - solution: sln
    - msbuild_build_project:
        - project: 'AndroidTestsApp\AndroidTestsApp.csproj'
        - targets : targets
        - configuration: 'Release;AdbTarget=-d -r'
    - run_android_nunit_tests:
        - touch_server: touch_server_exe
        - activity: 'com.sample.tests.app/com.sample.tests.app.MainActivity'
        - results_file : 'deployment\TestsResult.xml'
        - ip: 10.38.10.134
        - port: 55555
    - grab_logcat_results:
        - log_file: 'deployment\logs.txt'
# finish
