---
# Build script
sln : 'AndroidTestsApp.sln'
csproj: 'AndroidTestsApp\AndroidTestsApp.csproj'
deployment_directory: 'deployment'
configuration: 'Release;AdbTarget=-d -r'
test_results_file: 'deployment\TestsResult.xml'
main_test_activity_name: 'com.sample.tests.app/com.sample.tests.app.MainActivity'
logcat_results_file: 'deployment\logs.txt'
file_path: 'C:\Users\maa\Dropbox\Projects\baide\samples\AndroidTestsApp\TestConfiguration\TestResultsConfig.cs'
file_template: 'file_templates_folder\t_TestResultsConfig.txt'
nuget: '..\utils\.nuget\NuGet.exe'
xamarin_component: '..\utils\xamarin-component\xamarin-component.exe'
touch_server_exe: '..\utils\Touch.Server.Android.exe'
targets:
    - Clean
    - Install
tasks:
    - clean_directory:
        - directory: 'deployment'
    - fulfill_file_template:
        - ip: 10.38.10.134
        - port: 55555
        - is_automated: true
        - is_remote: true
        - format: nunit2
        - template: file_template
        - destination: file_path
    - restore_nuget_packages:
        - nuget_exe : nuget
        - solution: sln
    - restore_xam_components:
        - xam_exe: xamarin_component
        - solution: sln
    - msbuild_build_project:
        - project: csproj
        - targets : targets
        - configuration: configuration
    - run_android_nunit_tests:
        - touch_server: touch_server_exe
        - activity: main_test_activity_name
        - results_file : test_results_file
        - ip: 10.38.10.134
        - port: 55555
    - grab_logcat_results:
        - log_file: logcat_results_file
# finish
